name: My Action
description: Simple composite action

runs:
  using: composite
  steps:
    - name: Hello
      shell: bash
      run: echo "Hello"

    - name: Welcome
      shell: bash
      run: echo "Welcome to Composite Action"
