name: My Action
description: My first composite action

runs:
  using: composite
  steps:
    - name: Print Hello
      shell: bash
      run: echo "Hello"

    - name: Print Welcome
      shell: bash
      run: echo "Welcome to Composite Action"
