name: Multiple Jobs Example

on:
  push:
    branches: [main]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message 1
        run: echo "Hello from Job 1"

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message 2
        run: echo "Hello from Job 2"
