name: Sequential Example

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start building"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "start Testing"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "start Deploying"
